apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-targets
  namespace: default
data:
  # Prometheus file_sd_configs 형식
  # 외부 GPU 서버 추가/제거 시 이 파일만 수정 후 kubectl apply
  targets.json: |
    [
      {
        "targets": [
          "183.111.14.6:9400"
        ],
        "labels": {
          "job": "dcgm-exporter",
          "site": "remote-datacenter",
          "node": "conb-gpu-node-1"
        }
      }
    ]

  node-targets.json: |
    [
      {
        "targets": [
          "183.111.14.6:9100"
        ],
        "labels": {
          "job": "node-exporter",
          "site": "remote-datacenter",
          "node": "conb-gpu-node-1"
        }
      }
    ]
